version: '3.8'

services:
  blog-submission:
    build: ./blog-submission
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  queue-consumer:
    build: ./queue-consumer
    depends_on:
      - kafka
      - elasticsearch

  search-api:
    build: ./search-api
    ports:
      - "3002:3002"
    depends_on:
      - elasticsearch

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
