
version: '3.8'

services:
  blog-submission:
    build: ./blog-submission
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    networks:
      - app-network

  queue-consumer:
    build: ./queue-consumer
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - app-network

  search-api:
    build: ./search-api
    ports:
      - "3002:3002"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

volumes:
  esdata:

networks:
  app-network:
    driver: bridge
